apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
data:
  init-db.sql: |
    CREATE DATABASE polardb_catalog;
    CREATE DATABASE polardb_order;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-postgres
  labels:
    db: polar-postgres
spec:
  selector:
    matchLabels:
      db: polar-postgres
  template:
    metadata:
      labels:
        db: polar-postgres
    spec:
      volumes:
        - name: init-script
          configMap:
            name: init-db-script  # Nombre del ConfigMap con el script SQL
      containers:
        - name: polar-postgres
          image: postgres:17.2
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: polar-postgres
  labels:
    db: polar-postgres
spec:
  type: ClusterIP
  selector:
    db: polar-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
