version: "3.8"
services:

  catalog-service:
    depends_on:
      - polar-postgres
    image: "ghcr.io/perinan/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001

  polar-postgres:
    image: "postgres:17.2"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
