version: "3.8"
services:

  order-service:
    depends_on:
      - catalog-service
    image: "order-service:0.0.3-SNAPSHOT"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - POLAR_CATALOG_SERVICE_URL=http://catalog-service:9001
      - RABBITMQ_HOST=polar-rabbitmq
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002

  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=testdata
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001

  config-service:
    image: "config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - 8888:8888

  polar-postgres:
    image: "postgres:17.2"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: "redis:bookworm"
    container_name: "polar-redis"
    ports:
      - 6379:6379

  polar-rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: "polar-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
